#
# Copyright 2022 NXP
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += imx93_hexabitz.o
obj-y += lpddr4x_timing.o
obj-y += lpddr4x_timing_1866mts.o
ifdef CONFIG_SPL_BUILD
obj-y += spl.o

endif

